name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make iso
    - uses: actions/upload-artifact@v3.1.3
      with:
        # Artifact name
        name: iso
        # A file, directory or wildcard pattern that describes what to upload
        path: mineassemble.iso
